version: '3'
services:
  webserver:
    build: .
    container_name: laravel-pin-input-server
    restart: unless-stopped
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
      - "3000:3000"
    links:
      - dbserver
    environment:
      - DB_HOST=dbserver
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
  dbserver:
    image: mysql:5.7
    container_name: laravel-pin-input-db
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  dbvol:
